services:
  frontend:
    container_name: frontend
    image: front:v1.0
    restart: unless-stopped
    ports:
      - '80:80'
    environment:
      - BACKEND_URL=http://backend:8080
    volumes:
      - ../frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      backend:
        condition: service_started
    networks:
      app_network:
        aliases:
          - frontend

  backend:
    container_name: backend
    image: back:v1
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      - MYSQL_DATABASE=eschool
      - DATASOURCE_URL=jdbc:mysql://eschool-mysql:3306/eschool?useUnicode=true&characterEncoding=utf8
      - DATASOURCE_USERNAME=root
      - DATASOURCE_PASSWORD=root
    depends_on:
      eschool-mysql:
        condition: service_healthy
    networks:
      app_network:
        aliases:
          - backend

  eschool-mysql:
    container_name: eschool-mysql
    image: mysql:lts
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=eschool
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app_network

networks:
  app_network:
    driver: bridge