apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
  namespace: eschool
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: prometheus
