# roles/prometheus/tasks/main.yml
- name: Create prometheus user
  user:
    name: prometheus
    shell: /bin/false
    system: yes

- name: Create Prometheus directories
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'
  loop:
    - /usr/local/prometheus
    - /usr/local/prometheus/data

- name: Install Prometheus dependencies
  apt:
    name: [wget, tar, curl]
    state: present
    update_cache: yes

- name: Download Prometheus
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v2.47.0/prometheus-2.47.0.linux-amd64.tar.gz"
    dest: /tmp/prometheus.tar.gz

- name: Extract Prometheus
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /opt/
    remote_src: yes

- name: Move Prometheus binaries
  copy:
    remote_src: yes
    src: /opt/prometheus-2.47.0.linux-amd64/
    dest: /usr/local/prometheus
    owner: prometheus
    group: prometheus
    mode: '0755'

- name: Create Prometheus config from template
  template:
    src: prometheus.yml.j2
    dest: /usr/local/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: '0644'

- name: Create Prometheus systemd service
  copy:
    dest: /etc/systemd/system/prometheus.service
    content: |
      [Unit]
      Description=Prometheus
      After=network.target

      [Service]
      User=prometheus
      Group=prometheus
      ExecStart=/usr/local/prometheus/prometheus \
        --config.file=/usr/local/prometheus/prometheus.yml \
        --storage.tsdb.path=/usr/local/prometheus/data
      Restart=always

      [Install]
      WantedBy=multi-user.target

- name: Reload and enable Prometheus
  systemd:
    daemon_reload: yes
    name: prometheus
    state: started
    enabled: yes
