version: '3.9'

services:
  frontend:
    container_name: frontend
    image: bilkovsky/frontend:latest
    restart: unless-stopped
    networks:
      - app_network

  backend:
    container_name: backend
    image: bilkovsky/backend:latest
    restart: unless-stopped
    environment:
      - DATASOURCE_URL=jdbc:mysql://10.161.0.3:3306/eschool?useUnicode=true&characterEncoding=utf8&createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      - DATASOURCE_USERNAME=appuser
      - DATASOURCE_PASSWORD=StrongPassword123!
    networks:
      - app_network

  nginx:
    container_name: nginx
    image: nginx:latest
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge
