version: '3.9'

services:
  frontend:
    container_name: frontend
    image: bilkovsky/frontend:latest
    restart: unless-stopped
    networks:
      - app_network
    volumes:
      - frontend_data:/usr/share/nginx/html:ro  # <- додаємо спільний volume

  backend:
    container_name: backend
    image: bilkovsky/backend:latest
    environment:
      - DATASOURCE_URL=jdbc:mysql://10.205.0.3:3306/eschool?useUnicode=true&characterEncoding=utf8&createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      - DATASOURCE_USERNAME=root
      - DATASOURCE_PASSWORD=root
    ports:
      - "8080:8080"
    networks:
      - app_network

  nginx:
    container_name: nginx
    image: nginx:latest
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - frontend_data:/usr/share/nginx/html:ro  # <- використовуємо ті ж файли
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge

volumes:
  frontend_data:
